default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: CI_CD_training_development

test:
  <<: *default
  database: CI_CD_training_test

production:
  <<: *default
  database: CI_CD_training_production
  username: CI_CD_training
  password: <%= ENV["CI_CD_TRAINING_DATABASE_PASSWORD"] %>
